pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url 'https://api.xposed.info/' } // Xposed API डाउनलोड करने के लिए यह बहुत ज़रूरी है!
    }
}

rootProject.name = "DynamicIslandLSPosed"
include ':app'
