pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    // PREFER_SETTINGS टकराव को रोकता है और बिल्ड को आसान बनाता है
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
        maven { url 'https://api.xposed.info/' }
    }
}

rootProject.name = "DynamicIslandLSPosed"
include ':app'
